### PR TITLE
Enhanced Contact Us section

### PR DESCRIPTION
**Pull request by ZaidMujahid**
## What is the change?
Changed the UI and made it look attractive and it is responsive also

## Related issue?
#104 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x ] I have commented my code, particularly in hard-to-understand areas.
-   [x ] My changes generates no new warnings.
-   [x ] I'm JWOC contributor.

##  Screenshots (if any)
Before:
Screenshot (101)
After:
Screenshot (102)
Screenshot (103)

### CODE REVIEW

**Review by Chaitalishetty — CHANGES_REQUESTED** [review]
@ZaidMujahid Great work 🤩!
Can you remove the background as it doesnot match the theme of the website?
image

Also can you make these two elements (the form and the illustrations) side by side in desktop view.

**Comment by ZaidMujahid** [comment]
What can I add in place of the previous background image? The same image with dark grey color will work?

**Comment by ZaidMujahid** [comment]
Or I can just add a plain background of the color of your choice

**Comment by ZaidMujahid** [comment]
Yes I can work on making the elements side by side, just confirm me about the background image or I'll share the designs on discord you can confirm from their

**Comment by Chaitalishetty** [comment]
You can keep the previous background color only which is there in other pages as well.

**Review by Chaitalishetty — APPROVED** [review]
Amazing work 🤩 !!

**Comment by ZaidMujahid** [comment]
@Chaitalishetty Mentor, Have you merged this PR under JWOC? Because I don't know how to check, please let me know, Thank you

**Comment by Chaitalishetty** [comment]
> @Chaitalishetty Mentor, Have you merged this PR under JWOC? Because I don't know how to check, please let me know, Thank you

Yes I have added the JWOC label for this PR.

**Pull request merged**
