### PR TITLE
Added Animated Background

### PR DESCRIPTION
**Pull request by riiyaaa**
Added animated background. The transparent boxes will float upwards.

animated backdrop

### CODE REVIEW

**Review by Chaitalishetty — CHANGES_REQUESTED** [review]
@riiyaaa Looks Amazing 🤩🤩 !
But can you make the boxes float downwards.

**Comment by Chaitalishetty** [comment]
> Added animated background. The transparent boxes will float upwards.
> 
> animated backdrop

Do mention and issue number here . Add stick to the pull request template that is given.

**Comment by riiyaaa** [comment]
> @riiyaaa Looks Amazing 🤩🤩 ! But can you make the boxes float downwards.

Okay I will try!

**Comment by riiyaaa** [comment]
@Chaitalishetty  I have made the requested changes. Please Review.

**Review by Chaitalishetty — APPROVED** [review]
Amazing work 🤩

**Comment by riiyaaa** [comment]
Thankyou for assigning it to me!

**Pull request merged**
