### PR TITLE
Preloader added

### PR DESCRIPTION
**Pull request by sorba160**
## What is the change?
I added a pre loader to the website.

## Related issue?
closes: Add Preloader #105

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x ] I have  checked there aren't other open [Pull Requests](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/pulls) for the same update/change.
-   [ x] I have you tested the code before submission.
-   [x ] I have commented my code, particularly in hard-to-understand areas.
-   [x ] My changes generates no new warnings.
-   [ x] I'm JWOC contributor.

### CODE REVIEW

**Comment by sorba160** [comment]
Pull request was unfortunately closed due to some technical problem, So I have re created it , and I think there is no need to create branch because I am working forking it to my account , so already I can have my code separately . @Chaitalishetty

**Comment by Chaitalishetty** [comment]
Okay fine ! But do make the necessary changes that I suggested

**Comment by sorba160** [comment]
@Chaitalishetty I updated the pre loader .

**Comment by Chaitalishetty** [comment]
Can you resolve the merge conflicts?

**Comment by sorba160** [comment]
> Can you resolve the merge conflicts?

@Chaitalishetty yeah I have resolved the conflict. Now you can merge it.

**Comment by Chaitalishetty** [comment]
Not able to see the preloader.

**Comment by sorba160** [comment]
> Not able to see the preloader.

image
I have updated the preloader.  I think this is the website is very fast so the preloader is not clearly visible. You configure the network to fast or slow 3G after inspecting you can clearly see it.

**Pull request closed without merging**
