### PR TITLE
Added more opportunities and enhanced the page with more design and responsiveness

### PR DESCRIPTION
**Pull request by SabariGanesh-K**
## What is the change?
Added more opportunities in opportunities section and enhanced the page.
Opportunities added:- GSOC,GSSOC,MLH Fellowship,GWOC and JWOC
## Related issue?
closes: Issue #109 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x ] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [ x] I have  checked there aren't other open [Pull Requests](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io/pulls) for the same update/change.
-   [x ] I have you tested the code before submission.
-   [x ] I have commented my code, particularly in hard-to-understand areas.
-   [ x] My changes generates no new warnings.
-   [x ] I'm JWOC contributor.

##  Screenshots (if any)
image
image

### CODE REVIEW

**Comment by SabariGanesh-K** [comment]
@Chaitalishetty You may check now .

**Review by Chaitalishetty — CHANGES_REQUESTED** [review]
This looks amazing 🤩🤩. Great work!
Just one thing can you make the cards a bit smaller in desktop view.

**Comment by SabariGanesh-K** [comment]
image
Is this okay ?? @Chaitalishetty

**Comment by SabariGanesh-K** [comment]
Now check the size of cards

**Review by Chaitalishetty — APPROVED** [review]
Amazing work 🤩 !!

**Pull request merged**
